export enum BULLET_ACTION {
  FLYING = 'BULLET_FLYING',
  SYNC_FLYING = 'SYNC_BULLET_FLYING',
  STOP = 'BULLET_STOP',
  SYNC_STOP = 'SYNC_BULLET_STOP',
  COLLIDED_OBSTACLE = 'COLLIDED_OBSTACLE',
  SYNC_COLLIDED_OBSTACLE = 'SYNC_COLLIDED_OBSTACLE',
}

export enum USER_ACTION {
  CREATE_ROOM = 'CREATE_ROOM',
  CREATE_ROOM_FEEDBACK = 'CREATE_ROOM_FEEDBACK',
  CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR',
}
