export enum BULLET_ACTION {
  FLYING = 'BULLET_FLYING',
  SYNC_FLYING = 'SYNC_BULLET_FLYING',
  STOP = 'BULLET_STOP',
  SYNC_STOP = 'SYNC_BULLET_STOP',
  COLLIDED_OBSTACLE = 'COLLIDED_OBSTACLE',
  SYNC_COLLIDED_OBSTACLE = 'SYNC_COLLIDED_OBSTACLE',
}
